### ISSUE TITLE
使用非UI进程可能会因为多进程问题导致调用方代码崩溃

### ISSUE THREAD

**Issue by Charlottenpl** [happylishang/CacheEmulatorChecker#35]
问题复现：项目中使用ContentProvider在应用启动时获取context，因为是多进程会初始化Application多次，而在非UI进程中的Application获取context时是获取不到的，引发空指针异常。

---

请问这个库在集成时可以不开新进程吗？

**Comment by happylishang** [comment]
可以不开，，单独进程主要出于担心模拟器检测的兼容问题，防止影响UI进程，
